version: '3.8'

volumes:
    phpsocket:

services:
  nginx:
    container_name: ${CONTAINER_NGINX}
    build: ./nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./src/${APP_NAME}:/var/www/html
      - phpsocket:/var/run
    depends_on:
      - php
    environment:
      - SERVER_NAME=${SERVER_NAME}

  php:
    container_name: ${CONTAINER_PHP}
    build: ./php
    ports:
      - '${XDEBUG_PORT}:9000'
    volumes:
      - ./src:/home/docker
      - phpsocket:/var/run
    depends_on:
      - db

  mysql:
    image: mysql:8
    container_name: ${CONTAINER_MYSQL}
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - ./db:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: ${CONTAINER_REDIS}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "./data:/data"