version: '3.8'

volumes:
    phpsocket:

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./src/${APP_NAME}:/var/www/html
      - phpsocket:/var/run
    depends_on:
      - php
    environment:
      - APP_NAME=${APP_NAME}

  php:
    container_name: php
    build: ./php
    ports:
      - '${XDEBUG_PORT}:9000'
    volumes:
      - ./src:/home/docker
      - phpsocket:/var/run
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
